[project]
name = "eda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "ibis-framework[databricks]==11.0.0",
    "pandas>=2.0,<3",
    "plotnine>=0.15.2",
    "polars>=1.37.1",
]
